package RTS.system_tests.rts1

import org.sireum._
import RTS._

// Do not edit this file as it will be overwritten if SystemTestArtifactGen is rerun

object Actuation_Subsystem_Outputs_Container_SlangCheck {

  case class NameProvider(name: String,
                          function: (Any, Any) => B)

  case class TestRow(testMethod: NameProvider,
                     testDescription: String,
                     profile: Actuation_Subsystem_Outputs_Container_Profile,
                     preStateCheck: (Any => B),
                     property: NameProvider)
}

trait Actuation_Subsystem_Outputs_Container_SlangCheck
  extends SystemTestSuite {


  def next(profile: Actuation_Subsystem_Outputs_Container_Profile): Option[Actuation_Subsystem_Outputs_Container] = {
    return Actuation_Subsystem_Outputs_Container_Profile.nextH(profile)
  }

  def freshRandomLib: RandomLib = {
    return Actuation_Subsystem_Outputs_Container_Util.freshRandomLib
  }

  def getProfiles: MSZ[Actuation_Subsystem_Outputs_Container_Profile] = {
    return MSZ(getDefaultProfile)
  }

  //------------------------------------------------
  //  Test Vector Profiles
  //
  //   ..eventually auto-generated from a descriptor
  //     of injection vector
  //------------------------------------------------

  def getDefaultProfile: Actuation_Subsystem_Outputs_Container_Profile = {
    return Actuation_Subsystem_Outputs_Container_Profile.getDefaultProfile
  }

  def disableLogsAndGuis(): Unit = {

    // disable the various guis
    System.setProperty("java.awt.headless", "true")

    // suppress ART's log stream
    art.ArtNative_Ext.logStream = new java.io.PrintStream(new java.io.OutputStream {
      override def write(b: Int): Unit = {}
    })

    // suppress the static scheduler's log stream
    art.scheduling.static.StaticSchedulerIO_Ext.logStream = new java.io.PrintStream(new java.io.OutputStream {
      override def write(b: Int): Unit = {}
    })
  }
}
