package RTS.system_tests

import org.sireum._
import RTS._

// Do not edit this file as it will be overwritten if SystemTestArtifactGen is rerun

object Actuation_Subsystem_Outputs_Container_Profile {

  // a call to next may result in an AssertionError which is an indication that
  // SlangCheck was unable to satisfy a field's filter.  Consider using
  // nextH instead
  def next(profile: Actuation_Subsystem_Outputs_Container_Profile): Actuation_Subsystem_Outputs_Container = {
    return Actuation_Subsystem_Outputs_Container (
      TPAU_tempPressA_actuator_output = profile.TPAU_tempPressA_actuator_output.nextB(),
      SAU_satActuator_actuator = profile.SAU_satActuator_actuator.nextB()
    )
  }

  // nextH will return None() if SlangCheck is unable to satisfy a field's filter
  def nextH(profile: Actuation_Subsystem_Outputs_Container_Profile): Option[Actuation_Subsystem_Outputs_Container] = {
    try {
      return Some(Actuation_Subsystem_Outputs_Container (
        TPAU_tempPressA_actuator_output = profile.TPAU_tempPressA_actuator_output.nextB(),
        SAU_satActuator_actuator = profile.SAU_satActuator_actuator.nextB()))
    } catch {
      case e: AssertionError =>
        // SlangCheck was unable to satisfy a datatype's filter
        return None()
    }
  }

  def getDefaultProfile: Actuation_Subsystem_Outputs_Container_Profile = {
    return Actuation_Subsystem_Outputs_Container_Profile (
      name = "Default Actuation_Subsystem_Outputs_Container_Profile Profile",
      numTests = 100,
      numTestVectorGenRetries = 100,

      TPAU_tempPressA_actuator_output = Actuation_Subsystem_Outputs_Container_Util.freshRandomLib,
      SAU_satActuator_actuator = Actuation_Subsystem_Outputs_Container_Util.freshRandomLib
    )
  }
}

case class Actuation_Subsystem_Outputs_Container_Profile (
  var name: String,
  var numTests: Z,
  var numTestVectorGenRetries: Z,

  var TPAU_tempPressA_actuator_output : RandomLib,
  var SAU_satActuator_actuator : RandomLib) extends org.sireum.$internal.MutableMarker {

  override def $clonable: Boolean = F

  override def $clonable_=(b: Boolean): org.sireum.$internal.MutableMarker = this

  override def $owned: Boolean = F

  override def $owned_=(b: Boolean): org.sireum.$internal.MutableMarker = this

  override def $clone: org.sireum.$internal.MutableMarker = this
}
