package isolette.system_tests.rst

import org.sireum._
import isolette._

// Do not edit this file as it will be overwritten if SystemTestArtifactGen is rerun

object Regulate_Subsystem_Outputs_Container_ProfileI_Ext {
  def next(profile: Regulate_Subsystem_Outputs_Container_Profile): Option[Regulate_Subsystem_Outputs_Container] = {
    try {
      return Some(Regulate_Subsystem_Outputs_Container (
        heat_control = profile.heat_control.nextIsolette_Data_ModelOn_OffType(),
        display_temperature = profile.display_temperature.nextIsolette_Data_ModelTemp_impl(),
        regulator_status = profile.regulator_status.nextIsolette_Data_ModelStatusType(),
        mode = profile.mode.nextIsolette_Data_ModelRegulator_ModeType()))
    } catch {
      case e: AssertionError =>
        // SlangCheck was unable to satisfy a datatype's filter
        return None()
    }
  }
}
