package isolette.system_tests.rst

import org.sireum._
import isolette._

// Do not edit this file as it will be overwritten if SystemTestArtifactGen is rerun

object Regulate_Subsystem_Inputs_Container_Profile {

  // a call to next may result in an AssertionError which is an indication that
  // SlangCheck was unable to satisfy a field's filter.  Consider using
  // nextH instead
  def next(profile: Regulate_Subsystem_Inputs_Container_Profile): Regulate_Subsystem_Inputs_Container = {
    return Regulate_Subsystem_Inputs_Container (
      lowerDesiredTempWStatus = profile.lowerDesiredTempWStatus.nextIsolette_Data_ModelTempWstatus_impl(),
      upperDesiredTempWStatus = profile.upperDesiredTempWStatus.nextIsolette_Data_ModelTempWstatus_impl(),
      currentTempWStatus = profile.currentTempWStatus.nextIsolette_Data_ModelTempWstatus_impl(),
      mode = profile.mode.nextIsolette_Data_ModelRegulator_ModeType(),
      internalFailure = profile.internalFailure.nextIsolette_Data_ModelFailure_Flag_impl()
    )
  }

  // nextH will return None() if SlangCheck is unable to satisfy a field's filter
  def nextH(profile: Regulate_Subsystem_Inputs_Container_Profile): Option[Regulate_Subsystem_Inputs_Container] = {
    try {
      return Some(Regulate_Subsystem_Inputs_Container (
        lowerDesiredTempWStatus = profile.lowerDesiredTempWStatus.nextIsolette_Data_ModelTempWstatus_impl(),
        upperDesiredTempWStatus = profile.upperDesiredTempWStatus.nextIsolette_Data_ModelTempWstatus_impl(),
        currentTempWStatus = profile.currentTempWStatus.nextIsolette_Data_ModelTempWstatus_impl(),
        mode = profile.mode.nextIsolette_Data_ModelRegulator_ModeType(),
        internalFailure = profile.internalFailure.nextIsolette_Data_ModelFailure_Flag_impl()))
    } catch {
      case e: AssertionError =>
        // SlangCheck was unable to satisfy a datatype's filter
        return None()
    }
  }

  def getDefaultProfile: Regulate_Subsystem_Inputs_Container_Profile = {
    return Regulate_Subsystem_Inputs_Container_Profile (
      name = "Default Regulate_Subsystem_Inputs_Container_Profile Profile",
      numTests = 100,
      numTestVectorGenRetries = 100,

      lowerDesiredTempWStatus = Regulate_Subsystem_Inputs_Container_Util.freshRandomLib,
      upperDesiredTempWStatus = Regulate_Subsystem_Inputs_Container_Util.freshRandomLib,
      currentTempWStatus = Regulate_Subsystem_Inputs_Container_Util.freshRandomLib,
      mode = Regulate_Subsystem_Inputs_Container_Util.freshRandomLib,
      internalFailure = Regulate_Subsystem_Inputs_Container_Util.freshRandomLib
    )
  }
}

case class Regulate_Subsystem_Inputs_Container_Profile (
  var name: String,
  var numTests: Z,
  var numTestVectorGenRetries: Z,

  var lowerDesiredTempWStatus : RandomLib,
  var upperDesiredTempWStatus : RandomLib,
  var currentTempWStatus : RandomLib,
  var mode : RandomLib,
  var internalFailure : RandomLib) extends org.sireum.$internal.MutableMarker {

  override def $clonable: Boolean = F

  override def $clonable_=(b: Boolean): org.sireum.$internal.MutableMarker = this

  override def $owned: Boolean = F

  override def $owned_=(b: Boolean): org.sireum.$internal.MutableMarker = this

  override def $clone: org.sireum.$internal.MutableMarker = this
}
